"""
Payment schemas — simulated booking confirmation models.

Used by:
  - Payment Agent (generates BookingConfirmation)
  - API layer (returns BookingConfirmation to frontend)
  - Frontend (renders booking success screen)

Note: No real payment processing occurs. This is a mock/simulation layer.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


# ─── Enums ───────────────────────────────────────────────────────────


class BookingStatus(str, Enum):
    """Status of a simulated booking."""

    PENDING = "pending"
    CONFIRMED = "confirmed"
    CANCELLED = "cancelled"
    FAILED = "failed"


# ─── Booking Confirmation ───────────────────────────────────────────


class BookingConfirmation(BaseModel):
    """
    Simulated travel booking confirmation.

    Generated by the Payment Agent after the user approves the itinerary.
    Contains a mock booking reference, cost summary, and status.
    No actual payment is processed.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
    )

    booking_reference: str = Field(
        ...,
        description="Unique booking reference ID (generated UUID).",
    )

    status: BookingStatus = Field(
        default=BookingStatus.CONFIRMED,
        description="Booking status: pending, confirmed, cancelled, or failed.",
    )

    # ── Summaries ────────────────────────────────────────────────

    flight_summary: str = Field(
        default="",
        description=(
            "Human-readable summary of booked flights. "
            "e.g., 'BOM → CDG, Air France AF 218, Jun 15 — Jun 22'"
        ),
    )

    hotel_summary: str = Field(
        default="",
        description=(
            "Human-readable summary of booked hotel. "
            "e.g., 'Hotel Le Marais, 7 nights, €120/night'"
        ),
    )

    itinerary_summary: Optional[str] = Field(
        default=None,
        description="Brief text summary of the full itinerary.",
    )

    # ── Costs ────────────────────────────────────────────────────

    flight_cost: float = Field(
        default=0.0,
        description="Total flight cost.",
        ge=0,
    )

    hotel_cost: float = Field(
        default=0.0,
        description="Total hotel cost.",
        ge=0,
    )

    estimated_total_cost: float = Field(
        ...,
        description="Estimated total cost for the entire trip.",
        ge=0,
    )

    currency: str = Field(
        default="USD",
        description="Currency for all cost figures.",
    )

    # ── Metadata ─────────────────────────────────────────────────

    num_travelers: int = Field(
        default=1,
        description="Number of travelers in this booking.",
        ge=1,
    )

    destination: Optional[str] = Field(
        default=None,
        description="Primary destination of the trip.",
    )

    start_date: Optional[str] = Field(
        default=None,
        description="Trip start date (YYYY-MM-DD).",
    )

    end_date: Optional[str] = Field(
        default=None,
        description="Trip end date (YYYY-MM-DD).",
    )

    timestamp: str = Field(
        ...,
        description="Booking creation timestamp in ISO 8601 format.",
    )

    confirmation_message: Optional[str] = Field(
        default=None,
        description="Friendly message to display to the user upon confirmation.",
    )
